### ISSUE TITLE
Doesn't work in alpine docker container

### ISSUE THREAD

**Issue by jfrolich** [cristianoc/genType#346]
```
sh: /opt/app/cms/node_modules/gentype/gentype.exe: not found
```
Graphq_ppx_re had the same problem:

https://github.com/baransu/graphql_ppx_re/issues/44
https://github.com/baransu/graphql_ppx_re/pull/60

**Comment by cristianoc** [comment]
@jfrolich are executables build on alpine compatible with other distributions and not the other way around?
These are the current Azure CI settings:
```
  - template: .ci/build-platform.yml
    parameters:
      platform: Linux
      vmImage: ubuntu-16.04
```
